# Generated by Django 4.2.23 on 2026-07-10 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_add_english_level_to_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='skill_conversacion',
            field=models.IntegerField(default=0, help_text='Nivel de conversación (0-3 estrellas)'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='skill_gramatica',
            field=models.IntegerField(default=0, help_text='Nivel de gramática (0-3 estrellas)'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='skill_vocabulario',
            field=models.IntegerField(default=0, help_text='Nivel de vocabulario (0-3 estrellas)'),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('clase_proxima', 'Clase Próxima'), ('evaluacion_subida', 'Evaluación Subida'), ('evaluacion_pendiente', 'Evaluación Pendiente'), ('estudiante_sin_evaluar', 'Estudiante Sin Evaluar'), ('clase_hoy', 'Clase Hoy'), ('evaluacion_vencida', 'Evaluación Vencida'), ('plan_vencimiento', 'Plan por Vencer')], max_length=30),
        ),
        migrations.AlterField(
            model_name='notificacionestudiante',
            name='tipo',
            field=models.CharField(choices=[('plan_asignado', 'Plan Asignado'), ('plan_vencimiento', 'Plan por Vencer'), ('plan_vencido', 'Plan Vencido'), ('clase_programada', 'Clase Programada'), ('evaluacion_disponible', 'Evaluación Disponible'), ('logro_desbloqueado', 'Logro Desbloqueado'), ('mensaje_profesor', 'Mensaje del Profesor'), ('recordatorio_pago', 'Recordatorio de Pago')], max_length=30),
        ),
    ]
