# Generated by Django 4.2.23 on 2026-07-10 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_customuser_skill_conversacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='reto_semana_progreso',
            field=models.IntegerField(default=0, help_text='Segmentos completados esta semana (0-7)'),
        ),
    ]
