# Generated by Django 4.2.23 on 2025-09-01 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_customuser_is_profesor_profesor'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('student', 'Estudiante'), ('profesor', 'Profesor'), ('admin', 'Administrador')], default='student', max_length=20),
        ),
    ]
