# Generated by Django 4.2.23 on 2026-07-10 19:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_customuser_reto_semana_progreso'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissionCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission_key', models.CharField(max_length=100)),
                ('dulces', models.IntegerField(default=0)),
                ('xp', models.IntegerField(default=0)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mission_completions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Completitud de Misión',
                'verbose_name_plural': 'Completitudes de Misiones',
                'ordering': ['-completed_at'],
                'unique_together': {('user', 'mission_key')},
            },
        ),
    ]
