# Generated by Django 4.2.23 on 2025-09-02 17:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_clase'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='estudiantes',
            field=models.ManyToManyField(blank=True, related_name='clases', to=settings.AUTH_USER_MODEL),
        ),
    ]
