# Generated by Django 4.2.23 on 2026-07-10 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_missioncompletion'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='reto_completados_total',
            field=models.IntegerField(default=0, help_text='Total de retos diarios completados'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='reto_fallidos_total',
            field=models.IntegerField(default=0, help_text='Total de retos diarios fallados'),
        ),
    ]
