# Generated by Django 4.2.23 on 2026-07-17 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_customuser_reto_intentos_fallidos_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='reto_fallidos_total',
            field=models.IntegerField(default=0, help_text='Total de retos diarios fallados (días con fallo)'),
        ),
        migrations.CreateModel(
            name='NotificacionAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('nuevo_estudiante', 'Nuevo Estudiante'), ('estudiante_eliminado', 'Estudiante Eliminado'), ('nueva_venta', 'Nueva Venta'), ('venta_pendiente', 'Venta Pendiente'), ('plan_por_vencer', 'Plan por Vencer'), ('plan_vencido', 'Plan Vencido'), ('nueva_clase', 'Nueva Clase Programada'), ('evaluacion_enviada', 'Evaluación Enviada'), ('evaluacion_pendiente', 'Evaluación Pendiente de Calificar'), ('sistema', 'Notificación del Sistema')], max_length=30)),
                ('titulo', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', max_length=10)),
                ('leida', models.BooleanField(default=False)),
                ('datos_adicionales', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_admin', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificación de Administrador',
                'verbose_name_plural': 'Notificaciones de Administradores',
                'ordering': ['-created_at'],
            },
        ),
    ]
