# Generated by Django 4.2.23 on 2025-09-05 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_bloque_evaluation_customuser_bloque_asignado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='bloque_asignado',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Bloque',
        ),
    ]
