# Generated by Django 4.2.23 on 2025-09-08 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_customuser_bloque_asignado_delete_bloque'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('video', 'Video'), ('image', 'Imagen')], max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('url', models.URLField()),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('author', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Videos', 'Videos'), ('Infografías', 'Infografías'), ('Fotos', 'Fotos')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Elemento Multimedia',
                'verbose_name_plural': 'Elementos Multimedia',
                'ordering': ['-created_at'],
            },
        ),
    ]
