# Generated by Django 4.2.23 on 2026-07-17 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_customuser_reto_fallidos_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacionestudiante',
            name='tipo',
            field=models.CharField(choices=[('plan_asignado', 'Plan Asignado'), ('plan_vencimiento', 'Plan por Vencer'), ('plan_vencido', 'Plan Vencido'), ('clase_programada', 'Clase Programada'), ('clase_proxima', 'Clase Próxima'), ('clase_hoy', 'Clase Hoy'), ('evaluacion_disponible', 'Evaluación Disponible'), ('mision_disponible', 'Misión Disponible'), ('reto_diario_disponible', 'Reto Diario Disponible'), ('logro_desbloqueado', 'Logro Desbloqueado'), ('mensaje_profesor', 'Mensaje del Profesor'), ('recordatorio_pago', 'Recordatorio de Pago')], max_length=30),
        ),
    ]
