# Generated by Django 4.2.23 on 2025-09-08 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_mediaitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaitem',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='gallery/'),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
