# Generated by Django 4.2.23 on 2026-08-31 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_notificacionestudiante_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clase',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clase',
            name='hora',
            field=models.CharField(blank=True, default='08:00', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='clase',
            name='profesor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
