# Generated by Django 4.2.23 on 2026-09-03 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_clase_fecha_alter_clase_hora_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubmaterial',
            name='url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
