# Generated by Django 4.2.23 on 2026-09-09 20:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_clubmaterial_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialDocente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('tipo_evento', models.CharField(choices=[('clase', 'Clase Dictada'), ('evaluacion', 'Evaluación Calificada'), ('observacion', 'Observación de Desempeño'), ('capacitacion', 'Capacitación Recibida'), ('reunion', 'Reunión de Facultad'), ('otro', 'Otro')], default='otro', max_length=20)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('archivo_adjunto', models.FileField(blank=True, null=True, upload_to='historial_docente/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profesor', models.ForeignKey(limit_choices_to={'role': 'profesor'}, on_delete=django.db.models.deletion.CASCADE, related_name='historial_docente', to=settings.AUTH_USER_MODEL)),
                ('registrado_por', models.ForeignKey(blank=True, help_text='Administrador que registró este evento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historiales_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial Docente',
                'verbose_name_plural': 'Historial Docente',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_rooms_estudiante', to=settings.AUTH_USER_MODEL)),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_rooms_profesor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sala de Chat',
                'verbose_name_plural': 'Salas de Chat',
                'unique_together': {('estudiante', 'profesor')},
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.chatroom')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mensaje de Chat',
                'verbose_name_plural': 'Mensajes de Chat',
                'ordering': ['created_at'],
            },
        ),
    ]
