# Generated by Django 4.2.23 on 2025-09-10 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_especializacion_customuser_especializacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='attendance_percentage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='classes_attended',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='student_status',
            field=models.CharField(choices=[('basico', 'Básico'), ('intermedio', 'Intermedio'), ('superior', 'Superior')], default='basico', max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='tasks_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='total_classes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='total_tasks',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='english_level',
            field=models.CharField(choices=[('A1', 'A1 - Principiante'), ('A2', 'A2 - Elemental'), ('B1', 'B1 - Intermedio'), ('B2', 'B2 - Intermedio Alto'), ('C1', 'C1 - Avanzado'), ('C2', 'C2 - Competencia')], default='A1', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='especializacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='api.especializacion'),
        ),
    ]
