# Generated by Django 4.2.23 on 2025-09-10 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_customuser_attendance_percentage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='attendance_percentage',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='classes_attended',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='student_status',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='tasks_completed',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='total_classes',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='total_tasks',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='english_level',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='especializacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudiantes', to='api.especializacion'),
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('quiz', 'Quiz'), ('examen', 'Examen'), ('tarea', 'Tarea')], default='quiz', max_length=20)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('publicada', 'Publicada'), ('archivada', 'Archivada')], default='borrador', max_length=20)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='evaluaciones/')),
                ('fecha_limite', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('estudiantes_asignados', models.ManyToManyField(blank=True, related_name='evaluaciones_asignadas', to=settings.AUTH_USER_MODEL)),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evaluación',
                'verbose_name_plural': 'Evaluaciones',
                'ordering': ['-created_at'],
            },
        ),
    ]
