# Generated by Django 4.2.23 on 2026-09-28 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_clase_codigo_asistencia_asistencia_pendiente'),
    ]

    operations = [
        migrations.CreateModel(
            name='CicloRetosRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(help_text='Fecha en que inició el ciclo actual del ranking')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ciclo de Ranking de Retos',
                'verbose_name_plural': 'Ciclos de Ranking de Retos',
            },
        ),
        migrations.AddField(
            model_name='club',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='hora',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
