# Generated by Django 4.2.23 on 2025-09-11 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_customuser_attendance_percentage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RespuestaEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo_respuesta', models.FileField(blank=True, null=True, upload_to='respuestas_evaluaciones/')),
                ('comentarios', models.TextField(blank=True, help_text='Comentarios adicionales del estudiante', null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('entregada', 'Entregada'), ('calificada', 'Calificada')], default='pendiente', max_length=20)),
                ('calificacion', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('retroalimentacion', models.TextField(blank=True, help_text='Retroalimentación del profesor', null=True)),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True)),
                ('fecha_calificacion', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_evaluaciones', to=settings.AUTH_USER_MODEL)),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='api.evaluacion')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('evaluacion', 'estudiante')},
            },
        ),
    ]
