# Generated by Django 4.2.23 on 2025-09-11 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_respuestaevaluacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='respuestaevaluacion',
            options={'verbose_name': 'Respuesta de Evaluación'},
        ),
        migrations.AlterUniqueTogether(
            name='respuestaevaluacion',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='respuestaevaluacion',
            name='advertencias',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='respuestaevaluacion',
            name='completado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='respuestaevaluacion',
            name='fecha_envio',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='respuestaevaluacion',
            name='respuestas_json',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='respuestaevaluacion',
            name='tiempo_gastado',
            field=models.IntegerField(default=0, help_text='Tiempo en segundos'),
        ),
        migrations.AlterField(
            model_name='respuestaevaluacion',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_evaluacion', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='respuestaevaluacion',
            unique_together={('estudiante', 'evaluacion')},
        ),
        migrations.RemoveField(
            model_name='respuestaevaluacion',
            name='archivo_respuesta',
        ),
        migrations.RemoveField(
            model_name='respuestaevaluacion',
            name='calificacion',
        ),
        migrations.RemoveField(
            model_name='respuestaevaluacion',
            name='comentarios',
        ),
        migrations.RemoveField(
            model_name='respuestaevaluacion',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='respuestaevaluacion',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='respuestaevaluacion',
            name='fecha_calificacion',
        ),
        migrations.RemoveField(
            model_name='respuestaevaluacion',
            name='fecha_entrega',
        ),
        migrations.RemoveField(
            model_name='respuestaevaluacion',
            name='retroalimentacion',
        ),
        migrations.RemoveField(
            model_name='respuestaevaluacion',
            name='updated_at',
        ),
    ]
