# Generated by Cascade: tracking de retos por categoría + skill expresiones
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_cicloretosranking_club_fecha_club_hora'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='skill_expresiones',
            field=models.IntegerField(default=0, help_text='Nivel de expresiones (0-3 estrellas)'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='reto_vocab_intentos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='reto_vocab_aciertos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='reto_gram_intentos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='reto_gram_aciertos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='reto_conv_intentos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='reto_conv_aciertos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='reto_expr_intentos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='reto_expr_aciertos',
            field=models.IntegerField(default=0),
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='dailychallengequestion',
                    name='categoria',
                    field=models.CharField(
                        choices=[
                            ('vocabulary', 'Vocabulario'),
                            ('grammar', 'Gramática'),
                            ('conversation', 'Conversación'),
                            ('expressions', 'Expresiones'),
                        ],
                        max_length=20,
                        default='vocabulary',
                    ),
                ),
            ],
        ),
    ]
