# Generated by Cascade: periodo de progreso por nivel de inglés
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_skills_por_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='nivel_fecha_inicio',
            field=models.DateField(
                blank=True,
                null=True,
                help_text='Fecha de inicio del periodo del nivel de inglés actual',
            ),
        ),
    ]
