# Generated by Django 4.2.23 on 2025-09-11 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_respuestaevaluacion_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuestaevaluacion',
            name='archivo_respuesta',
            field=models.FileField(blank=True, null=True, upload_to='respuestas/'),
        ),
    ]
