# Generated by Django 4.2.23 on 2025-09-11 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_respuestaevaluacion_archivo_respuesta'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='clase',
            name='duracion',
            field=models.IntegerField(default=60, help_text='Duración en minutos'),
        ),
        migrations.AddField(
            model_name='clase',
            name='hora',
            field=models.CharField(default='08:00', max_length=20),
        ),
        migrations.AddField(
            model_name='clase',
            name='meet_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clase',
            name='modalidad',
            field=models.CharField(choices=[('virtual', 'Virtual'), ('presencial', 'Presencial')], default='virtual', max_length=20),
        ),
        migrations.AddField(
            model_name='clase',
            name='tema',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='clase',
            name='tipo_clase',
            field=models.CharField(choices=[('individual', 'Individual'), ('grupal', 'Grupal')], default='individual', max_length=20),
        ),
    ]
