# Generated by Django 4.2.23 on 2025-09-11 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_clase_descripcion_clase_duracion_clase_hora_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='estado',
            field=models.CharField(choices=[('programada', 'Programada'), ('activa', 'Activa'), ('completada', 'Completada')], default='programada', max_length=20),
        ),
    ]
