# Generated by Django 4.2.23 on 2025-09-12 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_clase_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('clase_proxima', 'Clase Próxima'), ('evaluacion_subida', 'Evaluación Subida'), ('evaluacion_pendiente', 'Evaluación Pendiente'), ('estudiante_sin_evaluar', 'Estudiante Sin Evaluar'), ('clase_hoy', 'Clase Hoy'), ('evaluacion_vencida', 'Evaluación Vencida')], max_length=30)),
                ('titulo', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', max_length=10)),
                ('leida', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clase_relacionada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.clase')),
                ('estudiante_relacionado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_sobre_mi', to=settings.AUTH_USER_MODEL)),
                ('evaluacion_relacionada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.evaluacion')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-created_at'],
            },
        ),
    ]
