# Generated by Django 4.2.23 on 2025-09-12 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_notificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuestaevaluacion',
            name='calificacion',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Calificación sobre 100', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='respuestaevaluacion',
            name='calificado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calificaciones_realizadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='respuestaevaluacion',
            name='comentarios_profesor',
            field=models.TextField(blank=True, help_text='Comentarios del profesor', null=True),
        ),
        migrations.AddField(
            model_name='respuestaevaluacion',
            name='fecha_calificacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
