# Generated by Django 4.2.23 on 2025-09-12 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_respuestaevaluacion_calificacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RachaEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('racha_actual', models.IntegerField(default=0)),
                ('mejor_racha', models.IntegerField(default=0)),
                ('ultima_actividad', models.DateField(auto_now=True)),
                ('total_dulces', models.IntegerField(default=0)),
                ('total_xp', models.IntegerField(default=0)),
                ('estudiante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='racha', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Racha de Estudiante',
                'verbose_name_plural': 'Rachas de Estudiantes',
            },
        ),
        migrations.CreateModel(
            name='RetoDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('vocabulario', 'Vocabulario'), ('gramatica', 'Gramática'), ('conversacion', 'Conversación'), ('lectura', 'Lectura'), ('escritura', 'Escritura')], max_length=20)),
                ('descripcion', models.CharField(max_length=200)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('completado', models.BooleanField(default=False)),
                ('fecha_completado', models.DateTimeField(blank=True, null=True)),
                ('puntos_obtenidos', models.IntegerField(default=0)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retos_diarios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reto Diario',
                'verbose_name_plural': 'Retos Diarios',
                'unique_together': {('estudiante', 'fecha', 'tipo')},
            },
        ),
        migrations.CreateModel(
            name='AsistenciaClase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('presente', 'Presente'), ('ausente', 'Ausente'), ('tardanza', 'Tardanza')], max_length=10)),
                ('minutos_tardanza', models.IntegerField(default=0, help_text='Minutos de tardanza si aplica')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='api.clase')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asistencia a Clase',
                'verbose_name_plural': 'Asistencias a Clases',
                'unique_together': {('estudiante', 'clase')},
            },
        ),
    ]
