# Generated by Django 4.2.23 on 2025-09-15 14:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_rachaestudiante_retodiario_asistenciaclase'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bloque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('nivel', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2')], max_length=2)),
                ('turno', models.CharField(choices=[('mañana', 'Mañana'), ('noche', 'Noche')], max_length=10)),
                ('misiones', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='rachaestudiante',
            name='estudiante',
        ),
        migrations.AlterUniqueTogether(
            name='retodiario',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='retodiario',
            name='estudiante',
        ),
        migrations.AlterField(
            model_name='clase',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('activa', 'Activa'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20),
        ),
        migrations.DeleteModel(
            name='AsistenciaClase',
        ),
        migrations.DeleteModel(
            name='RachaEstudiante',
        ),
        migrations.DeleteModel(
            name='RetoDiario',
        ),
        migrations.AddField(
            model_name='bloque',
            name='clases',
            field=models.ManyToManyField(related_name='bloque', to='api.clase'),
        ),
        migrations.AddField(
            model_name='bloque',
            name='estudiantes',
            field=models.ManyToManyField(limit_choices_to={'role': 'student'}, related_name='bloque_inscrito', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bloque',
            name='profesores',
            field=models.ManyToManyField(limit_choices_to={'role': 'profesor'}, related_name='bloques_asignados', to=settings.AUTH_USER_MODEL),
        ),
    ]
