# Generated by Django 4.2.23 on 2025-09-17 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_rachaestudiante_retodiario_asistenciaclase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rachaestudiante',
            name='estudiante',
        ),
        migrations.AlterUniqueTogether(
            name='retodiario',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='retodiario',
            name='estudiante',
        ),
        migrations.DeleteModel(
            name='AsistenciaClase',
        ),
        migrations.DeleteModel(
            name='RachaEstudiante',
        ),
        migrations.DeleteModel(
            name='RetoDiario',
        ),
    ]
