# Generated by Django 4.2.23 on 2025-09-18 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_bloque_remove_rachaestudiante_estudiante_and_more'),
        ('api', '0024_plan_venta_alter_clase_estado_alter_customuser_role_and_more'),
    ]

    operations = [
    ]
