# Generated by Django 4.2.23 on 2025-10-17 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_merge_20250918_1334'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bloque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del turno: Mañana, Tarde, Noche', max_length=50)),
                ('nivel', models.CharField(help_text='Nivel: A1, A2, B1, B2, C1, C2', max_length=10)),
                ('estado', models.CharField(default='configurado', help_text='Estado del bloque', max_length=20)),
                ('grupo_color', models.CharField(default='#FFC107', help_text='Color en formato hexadecimal', max_length=7)),
                ('horario_inicio', models.TimeField(blank=True, help_text='Hora de inicio del bloque', null=True)),
                ('horario_fin', models.TimeField(blank=True, help_text='Hora de fin del bloque', null=True)),
                ('cupo_maximo', models.IntegerField(default=20, help_text='Número máximo de estudiantes')),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bloque',
                'verbose_name_plural': 'Bloques',
                'ordering': ['nivel', 'nombre'],
                'unique_together': {('nombre', 'nivel')},
            },
        ),
    ]
