# Generated by Django 4.2.23 on 2025-11-04 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_customuser_correo_personal_bloque'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissionExternalLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission_key', models.SlugField(max_length=60)),
                ('platform', models.CharField(choices=[('gimkit', 'Gimkit'), ('kahoot', 'Kahoot'), ('quizizz', 'Quizizz'), ('custom', 'Custom')], default='custom', max_length=16)),
                ('url', models.URLField()),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Enlace de Misión',
                'verbose_name_plural': 'Enlaces de Misiones',
                'ordering': ['mission_key', '-created_at'],
                'indexes': [models.Index(fields=['mission_key', 'is_active'], name='api_mission_mission_4a0819_idx')],
            },
        ),
    ]
