# Generated by Django 4.2.23 on 2025-11-04 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_customuser_correo_personal_missionexternallink'),
    ]

    operations = [
        migrations.AddField(
            model_name='missionexternallink',
            name='audience_type',
            field=models.CharField(choices=[('global', 'Global'), ('bloque', 'Por Bloque'), ('student', 'Por Estudiante')], default='global', max_length=10),
        ),
        migrations.AddField(
            model_name='missionexternallink',
            name='audience_value',
            field=models.CharField(blank=True, help_text='Bloque (p.ej. B2_Mañana) cuando audience=bloque', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='missionexternallink',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Usuario específico cuando audience=student', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='missionexternallink',
            index=models.Index(fields=['mission_key', 'audience_type'], name='api_mission_mission_c8845b_idx'),
        ),
    ]
