# Generated by Django 4.2.23 on 2025-11-07 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_customuser_correo_personal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='correo_personal',
            field=models.EmailField(blank=True, help_text='Correo personal para recuperación de contraseña', max_length=254, null=True),
        ),
    ]
