# Generated by Django 4.2.23 on 2025-11-07 19:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_customuser_correo_personal'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroEliminacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='Nombre de usuario', max_length=150)),
                ('email', models.EmailField(help_text='Correo electrónico', max_length=254)),
                ('first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('cedula', models.CharField(blank=True, max_length=20, null=True)),
                ('nivel', models.CharField(blank=True, help_text='Nivel en el que estaba', max_length=20, null=True)),
                ('bloque_asignado', models.CharField(blank=True, max_length=50, null=True)),
                ('especializacion', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_registro', models.DateTimeField(help_text='Fecha en que se registró originalmente')),
                ('fecha_eliminacion', models.DateTimeField(auto_now_add=True, help_text='Fecha de eliminación')),
                ('dias_registrado', models.IntegerField(default=0, help_text='Días que estuvo registrado')),
                ('razon', models.CharField(choices=[('termino_clases', 'Terminó sus clases'), ('no_pago', 'No realizó el pago'), ('abandono', 'Abandonó el curso'), ('solicitud_propia', 'Solicitud del estudiante'), ('comportamiento', 'Problemas de comportamiento'), ('cambio_horario', 'No se adaptó al horario'), ('otro', 'Otra razón')], default='otro', max_length=50)),
                ('descripcion_adicional', models.TextField(blank=True, help_text='Detalles adicionales', null=True)),
                ('plan_activo', models.CharField(blank=True, max_length=100, null=True)),
                ('deuda_pendiente', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('notas', models.TextField(blank=True, help_text='Notas adicionales del administrador', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('eliminado_por', models.ForeignKey(help_text='Administrador que realizó la eliminación', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eliminaciones_realizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Eliminación',
                'verbose_name_plural': 'Registros de Eliminación',
                'ordering': ['-fecha_eliminacion'],
            },
        ),
    ]
