# Generated by Django 4.2.23 on 2025-11-10 21:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_asistencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('por_vencer', 'Por Vencer'), ('vencida', 'Vencida'), ('cancelada', 'Cancelada')], default='activa', max_length=20)),
                ('clases_totales', models.IntegerField(default=0, help_text='Total de clases incluidas en el plan')),
                ('clases_tomadas', models.IntegerField(default=0, help_text='Clases ya tomadas')),
                ('recordatorio_enviado', models.BooleanField(default=False)),
                ('fecha_recordatorio', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suscripciones', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suscripciones', to='api.plan')),
                ('venta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='suscripcion', to='api.venta')),
            ],
            options={
                'verbose_name': 'Suscripción',
                'verbose_name_plural': 'Suscripciones',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
