# Generated by Django 4.2.23 on 2025-11-11 19:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_suscripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacionEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('plan_vencimiento', 'Plan por Vencer'), ('plan_vencido', 'Plan Vencido'), ('clase_programada', 'Clase Programada'), ('evaluacion_disponible', 'Evaluación Disponible'), ('logro_desbloqueado', 'Logro Desbloqueado'), ('mensaje_profesor', 'Mensaje del Profesor'), ('recordatorio_pago', 'Recordatorio de Pago')], max_length=30)),
                ('mensaje', models.TextField()),
                ('leida', models.BooleanField(default=False)),
                ('datos_adicionales', models.JSONField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_estudiante', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificación de Estudiante',
                'verbose_name_plural': 'Notificaciones de Estudiantes',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
