# Generated by Django 4.2.23 on 2025-11-24 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_notificacionestudiante'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bloque',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='bloque_asignado',
        ),
    ]
