# Generated by Django 4.2.23 on 2025-11-25 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_delete_bloque_remove_customuser_bloque_asignado'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyChallengeQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.TextField()),
                ('categoria', models.CharField(choices=[('vocabulary', 'Vocabulario'), ('grammar', 'Gramática'), ('conversation', 'Conversación'), ('general', 'General')], default='general', max_length=20)),
                ('nivel', models.CharField(blank=True, help_text='Nivel sugerido (A1, A2, B1, etc.)', max_length=50, null=True)),
                ('opcion_a', models.CharField(max_length=255)),
                ('opcion_b', models.CharField(max_length=255)),
                ('opcion_c', models.CharField(blank=True, max_length=255, null=True)),
                ('opcion_d', models.CharField(blank=True, max_length=255, null=True)),
                ('respuesta_correcta', models.CharField(choices=[('A', 'Opción A'), ('B', 'Opción B'), ('C', 'Opción C'), ('D', 'Opción D')], max_length=1)),
                ('explicacion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Reto Diario',
                'verbose_name_plural': 'Retos Diarios',
                'ordering': ['-created_at'],
            },
        ),
    ]
