# Generated by Django 4.2.23 on 2025-12-10 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_dailychallengequestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='reto_mejor_racha',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='reto_racha_actual',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='reto_ultima_fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='total_dulces',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='total_xp',
            field=models.IntegerField(default=0),
        ),
    ]
